### ISSUE TITLE
Problem Compiling Program

### ISSUE THREAD

**Issue by anshess** [msesia/knockoffzoom-v2#1]
Hi,

I'm trying to compile your program, but I'm running into some problems. When I run make, I get the following error:
In file included from src/utils.cpp:4:0:
src/utils.h:27:42: fatal error: boost/integer/integer_log2.hpp: No such file or directory
 #include <boost/integer/integer_log2.hpp>
                                          ^
compilation terminated.

**Comment by msesia** [comment]
Thanks for reporting this problem. It seems to be compiling correctly in Linux as far as I can see, but it doesn't on Mac. I'm working to fix that.
Just out of curiosity, what system are you using?

**Comment by anshess** [comment]
Thanks, compilation works now.
